--Go to the directory, which contains create.sql 
--db2 -td"^" -f create.sql
--db2se enable_db sample
--create bufferpool bp8k pagesize 8 k^
--create system temporary tablespace tmpsys8k pagesize 8 k bufferpool bp8k^
--db2 connect to sample^

drop table restaurant^
drop table school^
drop table user^
drop table contact^
drop table forum^
drop table forumPost^
drop table profile^
drop table favoriteHouse^
drop table message^


create table restaurant 
(
	name varchar(50), 
	street varchar (50),
	city varchar (40),
	state char(2),
	zip char(5),
	county varchar(40),
	long double,
	lat double,
	loc DB2GSE.ST_POINT
)^

create table school 
(
	name varchar(50), 
	street varchar (50),
	city varchar (40),
	state char(2),
	zip char(5),
	county varchar(40),
	long double,
	lat double,
	loc DB2GSE.ST_POINT
)^

create table user
(
	email varchar(50) not null,
	firstn varchar (50) not null,
	lastn varchar (50) not null,
	password varchar(12)not null,
	primary key(email)
)^

create table contact
(
	fisrtn varchar (50) not null,
	lastn varchar (50) not null,
	email varchar(50) not null,
	message varchar(1000) not null
)^

create table forum 
(
	id_house integer not null generated by default as identity 
	(start with 1 increment by 1, no cache) primary key, 
	email varchar(50) not null references user(email) on delete cascade,
	title varchar(200) not null,
	contentForum varchar(1000) not null,
	timeForum timestamp not null
)^

create table forumPost
(
	id_house integer not null references forum(id_house) on delete cascade,
	email varchar(50) not null references user(email) on delete cascade,
	contentPost varchar(1000) not null,
	timePost timestamp not null
)^

create table profile
(
	email varchar(50) not null references user(email) on delete cascade,
	Occupation varchar(25),
	Gender varchar(10),
	Hobbies varchar(100)
)^

create table favoriteHouse
(
	email varchar(50) not null references user(email) on delete cascade,
	id_house integer not null references forum(id_house) on delete cascade,
	favoriteHouse varchar(200),
	addingTime timeStamp

)^

create table message 
(
	userIDsender varchar(50) not null references user(email) on delete cascade,
	userIDreceiver varchar(50) not null references user(email) on delete cascade,
	subject varchar(100) not null,
	content varchar(1000) not null,
	timeMessage timestamp not null
)^