--db2 -td"^" -f create.sql

--create bufferpool bp8k pagesize 8 k^
--create system temporary tablespace tmpsys8k pagesize 8 k bufferpool bp8k^
--db2se enable_db cs174^

drop table restaurant^
drop table school^
drop table user^
drop table forum^
drop table forumpost^
drop table profile^
drop table favoritehouse^
drop table message^
drop table sex_offenders^

create table restaurant 
(
	name varchar(50), 
	street varchar (50),
	city varchar (40),
	state char(2),
	zip char(5),
	county varchar(40),
	long double,
	lat double,
	loc DB2GSE.ST_POINT
)^

create table school 
(
	name varchar(50), 
	street varchar (50),
	city varchar (40),
	state char(2),
	zip char(5),
	county varchar(40),
	long double,
	lat double,
	loc DB2GSE.ST_POINT
)^

create table user
(
	userID integer not null generated by default as identity 
	(start with 100 increment by 1, no cache) primary key,
	firstname varchar (50) not null,
	lastname varchar (50) not null,
	email varchar(50) not null,
	password varchar(12)not null
)^

create table forum 
(
	id_house integer not null generated by default as identity 
	(start with 1 increment by 1, no cache) primary key, 
	userID int not null references user(userID) on delete cascade,
	title varchar(200) not null,
	contentForum varchar(1000) not null,
	timeForum timestamp not null
)^

create table forumPost
(
	id_house integer not null references forum(id_house) on delete cascade,
	userID int not null references user(userID) on delete cascade,
	contentPost varchar(1000) not null,
	timePost timestamp not null
)^

create table profile
(
	userID int not null references user(userID) on delete cascade,
	Occupation varchar(25),
	Gender varchar(10),
	Hobbies varchar(100)
)^

create table favoriteHouse
(
	userID int not null references user(userID) on delete cascade,
	id_house integer not null references forum(id_house) on delete cascade,
	favoriteHouse varchar(200),
	addingTime timeStamp

)^

create table message 
(
	userIDsender int not null references user(userID) on delete cascade,
	userIDreceiver int not null references user(userID) on delete cascade,
	subject varchar(100) not null,
	content varchar(1000) not null,
	timeMessage timestamp not null
)^

CREATE TABLE  sex_offenders(
	last_name	varchar(128),
	first_name	varchar(128),
	dob		varchar(16),	
	gender			varchar(16),	
	addr_street		varchar(64),	
	addr_city		varchar(32),
	addr_state		char(2),
	addr_zip		char(5),
	location		db2gse.st_point,
	photo		varchar(20)
	)^

list tables^

insert into user (firstname, lastname, email, password) values ('Luan', 'Bui', 'mluan1110@gmail.com', 'pass')^
select * from user^