connect to stlec1 user sysadm using c0deshop^ 

drop table user^ 
drop table profile^
drop table favoritehouse^  

create table user
(
	userID integer not null generated by default as identity 
	(start with 100 increment by 1, no cache) primary key,
	firstname varchar (50) not null,
	lastname varchar (50) not null,
	email varchar(50) not null,
	password varchar(12)not null
)^
 
create table profile
(
	userID int not null references user(userID) on delete cascade,
	Occupation varchar(25),
	Gender varchar(10),
	Hobbies varchar(100)
)^

create table favoriteHouse
(
	userID int not null references user(userID) on delete cascade,
	id_house integer not null references house(MLSNumber) on delete cascade,
)^
  
--test user log in
insert into user (firstname, lastname, email, password) values ('Luan', 'Bui', 'mluan1110@gmail.com', 'pass')^
insert into user (firstname, lastname, email, password) values ('Tran', 'Lam', 'tblam55@gmail.com', 'tran')^

select * from user^

select name, owner from sysibm.systables where owner = 'SYSADM'^
